spring:
  cloud:
    gateway:
      globals:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - UPDATE
              - DELETE